### ISSUE TITLE
Provide acknowledgments to Github editors of each code

### ISSUE THREAD

**Issue by valbert4** [errorcorrectionzoo/eczoo_data#218]
We'd like to edit all YaML code files to include information about their contributors in a new meta field. Currently, this information is stored in the git commits of those files.

The solution is to write a one-time script that crawls through the code files and performs the necessary changes automatically.

Requirements:
- add a field in all YaML code files in the `eczoo_data` repository:
```yaml
_meta:
  contributors:
    - name: ...
       githubusername: ...
    - name: ...
       githubusername: ...
```
- The contributors should be extracted from the git history of that file, by examining the authors of commits to that file. Contributors should be listed in chronological order of their contributions. Contributors that contributed only typos or minimal edits should not be listed. (Let's say fixing a typo -> no; adding a few sentences -> yes. We might have to decide on a more precise rule.)
- The full name of the contributor should also be listed along their github user name. This is to ensure that even if the user deletes their github account, we still at least have the name of the contributor that is listed in the meta field.

**Comment by cometta** [comment]
PR at https://github.com/errorcorrectionzoo/eczoo_generator/pull/10
