### ISSUE TITLE
Quantum double codes are incorrectly listed as descendants of stabilizer codes

### ISSUE THREAD

**Issue by alexcowtan** [errorcorrectionzoo/eczoo_data#302]
Quantum double codes are not stabilizer in general (only in the Abelian case), and so should not be classed as a descendent of stabilizer codes, assuming that A is a child of B iff A is a subset of B. It looks like this issue stems from the claim that group-GKP codes have CSS codes as a parent, then that quantum double codes are a child of group-GKP codes. Group-GKP codes should not have CSS codes as parents, if my assumption about subset-inclusion is correct.

I have not made the change myself as a pull request, as I am unfamiliar with the ECZoo and I may have misunderstood the intended child/parent structure.

**Comment by valbert4** [comment]
That's correct, thanks for pointing this out and, just as importantly, tracking where the parent error was. CSS is now a cousin of group_gkp. I added you to the list of contributors.

The X,Z type operators of group GKP codes are not unitary, but the flavor of stab codes is there. That direction could be developed further.
