### ISSUE TITLE
Smallest stabilizer code with transversal T

### ISSUE THREAD

**Issue by chrispattison2** [errorcorrectionzoo/eczoo_data#328]
The transversal gates section of the [15 qubit code](https://errorcorrectionzoo.org/c/stab_15_1_3) claims that it is the smallest qubit stabilizer code with a transversal gate outside the Clifford group. Maybe this should either read "strongly transversal gate" or "weakly transversal T-gate" since there is an [8 qubit code](https://errorcorrectionzoo.org/c/stab_8_3_2) with weakly transversal CCZ.

I don't know much about gates, so maybe I am misunderstanding

**Comment by valbert4** [comment]
THanks, edited.
