### ISSUE TITLE
Quantum Reed-Muller Codes

### ISSUE THREAD

**Issue by ChrisPattison** [errorcorrectionzoo/eczoo_data#336]
The page on Quantum Reed-Muller codes `codes/quantum/qubits/rm/quantum_reed_muller.yml` claims that 

> Additionally, CSS codes formed from binary Reed-Muller codes achieve channel capacity on erasure channels [[2]](https://errorcorrectionzoo.org/c/quantum_reed_muller#citation-2).

This cites a result about [classical Reed-Muller codes on classical erasure channels](https://arxiv.org/abs/1601.04689). I'm not sure how this could follow in a straightforward way from this paper. It's worth noting that the capacity of the quantum erasure channel [isn't even positive for erasure fraction greater than 1/3](https://arxiv.org/abs/quant-ph/9701015)

**Comment by valbert4** [comment]
Thanks for pointing this out. I meant this ref:  10.1109/ISIT.2016.7541599
<https://doi.org/10.1109/ISIT.2016.7541599>

Best,
Victor
