### ISSUE TITLE
Qubit CSS code and Clifford group

### ISSUE THREAD

**Issue by jcbesseETH** [errorcorrectionzoo/eczoo_data#337]
The statement ' All CSS codes admit transversal Pauli and CNOT gates [[16]](https://errorcorrectionzoo.org/c/qubit_css#citation-16). Self-dual CSS codes admit a transversal Hadamard, completing the Clifford group.' seems wrong. One is still missing the S gate at this point.

**Comment by valbert4** [comment]
Thanks, fixed!
