### ISSUE TITLE
Having a precise definition of mathematical symbols appear on the desctription

### ISSUE THREAD

**Issue by zoome0215** [errorcorrectionzoo/eczoo_data#344]
Hi,
I was thinking 
if one could put the definitions of 
Theta(n), Omega(n), carly O(n)
and so on which appears in various places, it would be great. I konw they are somehow differentiated by upper bound, lower bound and so on, but it get's very hard to keep track of, when I'm not familiar with the field enough. Any help on this will be greatly appreciated!

**Comment by valbert4** [comment]
Section added here, with links at relevant places where I could find them. Please let us know any inconsistencies. https://errorcorrectionzoo.org/c/block
