### ISSUE TITLE
Manual citation format

### ISSUE THREAD

**Issue by Kee-Wang** [errorcorrectionzoo/eczoo_data#41]
I might be wrong, but can someone confirm that the manual citation seems to require \cite{manual_citation_minilatex: ...}, instead of simply \cite{manual: ...}?  Check this [line](https://github.com/errorcorrectionzoo/eczoo_generator/blob/343eb88b1e68f56b17fd9f28d0f6b981ae81c717/ecczoogen/citationmanager/__init__.py#L104).

**Comment by phfaist** [comment]
Wow, good catch, thanks! I fixed the generator code in [this commit](https://github.com/errorcorrectionzoo/eczoo_generator/commit/0e7be4582574cc6270ff5472aa98b493febff119), you can use `\cite{manual:{...}}` as advertised. Thanks for spotting this bug.
