### ISSUE TITLE
arXiv vs doi citation format issue

### ISSUE THREAD

**Issue by Kee-Wang** [errorcorrectionzoo/eczoo_data#43]
There is a slight caveat when using the \cite{arXiv:...} instead of \cite{doi:...}.

I just encountered an interesting case where the arXiv is not able to provide the correct doi:
`\cite{arXiv:1604.04062}` will lead to the same citation as `\cite{doi:10.26421/QIC16.15-16}` as stated on [arxiv.org](https://arxiv.org/abs/1604.04062), which results in:
`“[]”, Quantum Information and Computation 16, (2016). DOI`,
while the correct citation should be:
`\cite{doi:10.26421/QIC16.15-16-1}`, which gives
`B. Criger and B. Terhal, “Noise thresholds for the [4,2,2]-concatenated toric code”, Quantum Information and Computation 16, 1261 (2016). DOI`
The DOI is wrong (or not specific enough) on the arXiv website in the first place. So it seems citing using  DOI can give a consistently reliable result.

**Comment by phfaist** [comment]
thanks for reporting! I'm working on a way to specify the DOI manually for certain arXiv citations to deal with cases like this one. In the meantime, please continue using arXiv identifiers in your citations, and mark the correct DOI somewhere in a comment in the YAML file so that we can add it to the exception list once it's ready. Thanks!

**Comment by Kee-Wang** [comment]
Got it. I will adapt this plan next time I pull-request.

**Comment by phfaist** [comment]
fixed! your citation should now render properly (if you're previewing the site locally, you'll need to pull both the data and the generator repos, and use `--skip-citation-cache` once to regenerate the citation cache).

**For future reference**: in case anyone else stumbles here with a similar problem. In such cases, one should add a line in `eczoo_data/citation_extra/citations_hints.yml` to associate the correct DOI with the given arXiv identifier. Use only in exceptional cases like this one.
