### ISSUE TITLE
Tex commands

### ISSUE THREAD

**Issue by valbert4** [errorcorrectionzoo/eczoo_data#95]
Implement tex command \ket{...} = \left|...\right\rangle

**Comment by phfaist** [comment]
This one should already work. Doesn't it?

**Comment by valbert4** [comment]
where can I do it so that it's valid for all code files?

**Comment by phfaist** [comment]
it should work everywhere already (as long as you're in math mode, of course).

**Comment by valbert4** [comment]
ha! i kept editing it to rangle and langle
